### Send POST request with json body
POST http://localhost:8082/api/v1/client/sign-in
Content-Type: application/json

{
  "email": "qmoskalov.a@gmail.com",
  "password": "password"
}

### Authentication by refresh token
POST http://localhost:8082/api/v1/client/sign-up
Content-Type: application/json

{
  "firstName": "Artem",
  "lastName": "Moskalov",
  "email": "qmoskalov@gmail.com",
  "password": "password",
  "emailConfirmUrl": "http://localhost:3000/email/confirmation"
}

### Sign-out
GET http://localhost:8082/api/v1/client/sign-out
Content-Type: application/json

### Sign-out // security
GET http://localhost:8082/api/v1/client/emails/confirmation?token=63a6044e-15bf-4149-a9df-13ff81f0bbe2
Content-Type: application/json